apiVersion: v1
kind: Namespace
metadata:
  name: my-baseline-namespace
  labels:
    # enforce: Policy violations will cause the pod to be rejected.
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.25 # specific minor version or "latest"

   # audit: Policy violations will trigger the addition of an audit annotation to the event recorded in the audit log, but are otherwise allowed.
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.25 

   # Policy violations will trigger a user-facing warning, but are otherwise allowed.
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.25
